ini_open("assa_save.ini");
ini_write_real("variables", "power", inssa_power);
ini_write_real("variables", "level", inssa_level);
ini_write_real("variables", "upgradelevel", upgrade_level);
ini_write_real("variables", "clicknumber", click_number);
ini_write_real("variables", "click_achievement_1", click_achievement_1);
ini_write_real("variables", "upgrade_achievement_1", upgrade_achievement_1);
ini_write_real("variables", "notice_achievement_click_1", notice_achievement_click_1);
ini_write_real("variables", "notice_achievement_upgrade_1", notice_achievement_upgrade_1);
ini_write_real("variables", "achievement_bar", achievement_bar);
ini_write_real("variables", "money", money);
ini_write_real("variables", "global_fever", global_fever);
ini_write_real("variables", "global_buy_window_realshop", global_buy_window_realshop);
ini_write_real("variables", "global_assa_cloth", global_assa_cloth);
ini_write_real("variables", "global_buy_cloth_blue", global_buy_cloth_blue);
ini_write_real("variables", "global_tutorial", global_tutorial);
ini_write_real("variables", "global_tutorial_work1", global_tutorial_work1);
ini_close();
